from django.urls import path

from .views import (
    BaseView,
    ProductDetailView,
    CategoryDetailView,
    CartView,
    AddToCartView,
    DeleteFromCartView,
    ChangeQTYView,
    CheckoutView,
    MakeOrderView,
    sale,
    AddReview,
    LogoutView,
    UserLoginView,
    ProfileView,
    AccountView,
    RegisterView,
    Register,
    PaymentOrder,
    FictionPayment,
    HistoryOrders,
    SearchView,
    CatalogView,
    OneOrderView,
    RepeatPayment,
    RestorePassword,
    AboutView,
)


urlpatterns = [
    path('', BaseView.as_view(), name='base'),
    path('products/<str:ct_model>/<str:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('catalog/<str:sort>/', CatalogView.as_view(), name='catalog'),
    path('category/<str:slug>/<str:sort>/', CategoryDetailView.as_view(), name='category_detail'),
    path('search/<str:sort>/', SearchView.as_view(), name='search'),
    path('cart/', CartView.as_view(), name='cart'),
    path('add-to-cart/<str:ct_model>/<str:slug>/', AddToCartView.as_view(), name='add_to_cart'),
    path('remove-from-cart/<str:ct_model>/<str:slug>/', DeleteFromCartView.as_view(), name='delete_from_cart'),
    path('change-qty/<str:ct_model>/<str:slug>/', ChangeQTYView.as_view(), name='change_qty'),
    path('orders/order', CheckoutView.as_view(), name='checkout'),
    path('orders/make_order', MakeOrderView.as_view(), name='make_order'),
    path('orders/oneorder/<int:pk>/', OneOrderView.as_view(), name='oneorder'),
    path('sale/', sale, name='sale'),
    path('add_review/<str:ct_model>/<str:slug>/', AddReview.as_view(), name='add_review'),
    path('users/profile/', ProfileView.as_view(), name='profile'),
    path('users/account/', AccountView.as_view(), name='account'),
    path('users/register/', RegisterView.as_view(), name='register'),
    path('users/logout/', LogoutView.as_view(), name='logout'),
    path('users/login/<int:flag>/', UserLoginView.as_view(), name='login'),
    path('users/restore_password/', RestorePassword.as_view(), name='restore_password'),
    path('order-register/', Register.as_view(), name='order_register'),
    path('orders/order_payment/', PaymentOrder.as_view(), name='order_payment'),
    path('orders/order_payment/fiction_payment/<int:pk>/', FictionPayment.as_view(), name='fiction_payment'),
    path('orders/repeat_payment/<int:pk>/', RepeatPayment.as_view(), name='repeat_payment'),
    path('users/history_order/', HistoryOrders.as_view(), name='history_order'),
    path('users/about/', AboutView.as_view(), name='about'),
]
