# Generated by Django 4.0.6 on 2022-07-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='limit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='limit',
            field=models.BooleanField(default=False),
        ),
    ]
