# Generated by Django 4.0.6 on 2022-07-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='review',
            name='object_id',
        ),
        migrations.AddField(
            model_name='notebook',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, to='mainapp.review'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, to='mainapp.review'),
        ),
    ]
