# Generated by Django 4.0.6 on 2022-07-16 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_review_content_type_remove_review_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='mainapp.review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer', verbose_name='Комментатор'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='mainapp.review'),
        ),
    ]
