# Generated by Django 4.0.6 on 2022-07-17 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_notebook_reviews_alter_review_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='tel',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
    ]
