# Generated by Django 4.0.6 on 2022-07-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_rename_phone_customer_tel_remove_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(null=True, upload_to='', verbose_name='Аватар'),
        ),
    ]
