# Generated by Django 4.0.6 on 2022-07-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_cartproduct_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='buying_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=30, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('Express delivery', 'Экспресс доставка'), ('Usual delivery', 'Обычная доставка')], default='Usual delivery', max_length=100, verbose_name='Способ доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Online card', 'Онлайн картой'), ('Online from someone  account', 'Онлайн с чужого счета')], default='Online card', max_length=100, verbose_name='Способ оплаты'),
        ),
    ]
