# Generated by Django 4.0.6 on 2022-07-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_remove_order_buying_type_remove_order_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='comment',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(max_length=100, verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(max_length=100, verbose_name='Способ оплаты'),
        ),
    ]
