# Generated by Django 4.0.6 on 2022-07-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_order_created_at_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateField(auto_now=True, verbose_name='Дата создания заказа'),
        ),
    ]
