# Generated by Django 4.0.6 on 2022-07-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='free_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notebook',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='free_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not_payment', 'Не оплачен'), ('in_progress', 'Доставляется'), ('is_ready', 'Заказ готов')], default='Не оплачен', max_length=100, verbose_name='Статус заказ'),
        ),
    ]
