# Generated by Django 4.0.6 on 2022-07-20 09:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_notebook_free_delivery_notebook_in_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='buy_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notebook',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 20, 9, 17, 31, 864852, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='buy_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 20, 9, 17, 31, 864852, tzinfo=utc)),
        ),
    ]
