# Generated by Django 4.0.6 on 2022-07-21 04:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_notebook_buy_count_notebook_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 21, 4, 42, 35, 16584, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 21, 4, 42, 35, 16584, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('limit', models.BooleanField(default=False)),
                ('free_delivery', models.BooleanField(default=False)),
                ('in_stock', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 7, 21, 4, 42, 35, 16584, tzinfo=utc))),
                ('buy_count', models.PositiveIntegerField(default=0)),
                ('processor_model', models.CharField(max_length=255, verbose_name='Модель процессора')),
                ('size', models.CharField(max_length=255, verbose_name='Габариты')),
                ('processor_freq', models.CharField(max_length=255, verbose_name='Частота процессора')),
                ('ram', models.CharField(max_length=255, verbose_name='Оперативная память')),
                ('video', models.CharField(max_length=255, verbose_name='Видеокарта')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
                ('reviews', models.ManyToManyField(blank=True, to='mainapp.review')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
