# Generated by Django 4.0.6 on 2022-07-21 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_alter_notebook_created_alter_smartphone_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Headphones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('limit', models.BooleanField(default=False)),
                ('free_delivery', models.BooleanField(default=False)),
                ('in_stock', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('buy_count', models.PositiveIntegerField(default=0)),
                ('weight', models.CharField(max_length=255, verbose_name='Вес')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет')),
                ('max_freq', models.CharField(max_length=255, verbose_name='Максимальная частота')),
                ('power', models.CharField(max_length=255, verbose_name='Мощность')),
                ('microphone', models.CharField(max_length=255, verbose_name='Микрофон')),
                ('noise_reduction', models.BooleanField(default=False, verbose_name='Шумоподавление')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
                ('reviews', models.ManyToManyField(blank=True, to='mainapp.review')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
