# Generated by Django 4.0.6 on 2022-07-24 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mainapp', '0019_alter_desktop_created_alter_notebook_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desktop',
            name='image',
        ),
        migrations.RemoveField(
            model_name='headphones',
            name='image',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='image',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='image',
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
