# Generated by Django 4.0.6 on 2022-07-25 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_notebookgallery_remove_desktop_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartphoneGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('smartphone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainapp.smartphone')),
            ],
        ),
        migrations.CreateModel(
            name='HeadphonesGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('headphones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainapp.headphones')),
            ],
        ),
        migrations.CreateModel(
            name='DesktopGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('desktop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainapp.desktop')),
            ],
        ),
    ]
