# Generated by Django 4.0.6 on 2022-07-30 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_desktop_image_headphones_image_notebook_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('limit', models.BooleanField(default=False)),
                ('free_delivery', models.BooleanField(default=False)),
                ('in_stock', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('buy_count', models.PositiveIntegerField(default=0)),
                ('weight', models.CharField(max_length=255, verbose_name='Вес')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет')),
                ('energy_consumption', models.CharField(max_length=255, verbose_name='Энергопотребление')),
                ('power', models.CharField(max_length=255, verbose_name='Мощность')),
                ('refrigerant', models.CharField(max_length=255, verbose_name='Хладагент')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
                ('reviews', models.ManyToManyField(blank=True, to='mainapp.review')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SmartWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('limit', models.BooleanField(default=False)),
                ('free_delivery', models.BooleanField(default=False)),
                ('in_stock', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('buy_count', models.PositiveIntegerField(default=0)),
                ('weight', models.CharField(max_length=255, verbose_name='Вес')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет')),
                ('energy_consumption', models.CharField(max_length=255, verbose_name='Энергопотребление')),
                ('power', models.CharField(max_length=255, verbose_name='Мощность')),
                ('display', models.CharField(max_length=255, verbose_name='Экран')),
                ('time_without_charge', models.CharField(max_length=255, verbose_name='Время работы аккумулятора')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
                ('reviews', models.ManyToManyField(blank=True, to='mainapp.review')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('limit', models.BooleanField(default=False)),
                ('free_delivery', models.BooleanField(default=False)),
                ('in_stock', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('buy_count', models.PositiveIntegerField(default=0)),
                ('weight', models.CharField(max_length=255, verbose_name='Вес')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет')),
                ('energy_consumption', models.CharField(max_length=255, verbose_name='Энергопотребление')),
                ('power', models.CharField(max_length=255, verbose_name='Мощность')),
                ('display', models.CharField(max_length=255, verbose_name='Экран')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
                ('reviews', models.ManyToManyField(blank=True, to='mainapp.review')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Washer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('limit', models.BooleanField(default=False)),
                ('free_delivery', models.BooleanField(default=False)),
                ('in_stock', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('buy_count', models.PositiveIntegerField(default=0)),
                ('weight', models.CharField(max_length=255, verbose_name='Вес')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет')),
                ('energy_consumption', models.CharField(max_length=255, verbose_name='Энергопотребление')),
                ('power', models.CharField(max_length=255, verbose_name='Мощность')),
                ('noise_level', models.CharField(max_length=255, verbose_name='Уровень шума')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
                ('reviews', models.ManyToManyField(blank=True, to='mainapp.review')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WasherGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('washer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainapp.washer')),
            ],
        ),
        migrations.CreateModel(
            name='TVGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('tv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainapp.tv')),
            ],
        ),
        migrations.CreateModel(
            name='SmartWatchGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('smartwatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainapp.smartwatch')),
            ],
        ),
        migrations.CreateModel(
            name='FridgeGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('fridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainapp.fridge')),
            ],
        ),
    ]
